stages:
  - build

appimage:
  stage: build
  image: ubuntu:14.04
  only:
    - master
    - /^release\-.+/
  script:
    - ./scripts/package appimage
  artifacts:
    paths:
    - build_*/ocs-store*.AppImage
    expire_in: 2 days
