#!/bin/bash

PKGNAME='pling-store'
PKGVER='5.0.1'
PKGREL='1'

UPDINFO="zsync|https://www.opencode.net/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/-/jobs/artifacts/${CI_COMMIT_REF_SLUG}/raw/build_pling-store/${PKGNAME}-${CI_COMMIT_REF_SLUG}-x86_64.AppImage.zsync?job=appimage"
APPDIR="${PKGNAME}.AppDir"

make
make DESTDIR=${APPDIR} prefix=/usr install

install -D -m 755 ${APPDIR}/usr/bin/${PKGNAME} ${APPDIR}/AppRun
install -D -m 644 ${APPDIR}/usr/share/applications/${PKGNAME}.desktop ${APPDIR}/${PKGNAME}.desktop
install -D -m 644 ${APPDIR}/usr/share/icons/hicolor/scalable/apps/${PKGNAME}.svg ${APPDIR}/${PKGNAME}.svg

install -D -m 755 /usr/lib/x86_64-linux-gnu/libgconf-2.so.4 ${APPDIR}/usr/lib/ocs-store-linux-x64/libgconf-2.so.4
install -D -m 755 /usr/lib/x86_64-linux-gnu/libXss.so.1 ${APPDIR}/usr/lib/ocs-store-linux-x64/libXss.so.1
install -D -m 755 /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libcanberra-gtk-module.so ${APPDIR}/usr/lib/ocs-store-linux-x64/libcanberra-gtk-module.so
install -D -m 755 /usr/lib/x86_64-linux-gnu/libgnome-keyring.so.0 ${APPDIR}/usr/lib/ocs-store-linux-x64/libgnome-keyring.so.0

curl -fsSL -o ocs-manager https://git.opendesktop.org/akiraohgaki/ocs-manager/uploads/d3dc42436b82d11360ebc96b38d4aaf4/ocs-manager-0.8.1-1-x86_64.AppImage
install -D -m 755 ocs-manager ${APPDIR}/usr/bin/ocs-manager

IMWHEEL_PATH=$(which imwheel)
install -D -m 755 ${IMWHEEL_PATH} ${APPDIR}/usr/bin/ocs-imwheel
install -D -m 644 imwheel.conf ${APPDIR}/usr/share/imwheel/.imwheelrc

curl -fsSL -o appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
chmod 755 appimagetool
./appimagetool --appimage-extract
./squashfs-root/AppRun -u "${UPDINFO}" ${APPDIR}

# Only timestamp development branches
if [ "${CI_COMMIT_REF_SLUG}" != "master" ]; then
  PKGREL=dev-${CI_COMMIT_SHORT_SHA}-$(date +"%Y%m%d-%H%M%S")
fi

# Fix url in zsync file
sed -i "/^URL:.*$/c\URL: ${PKGNAME}-${PKGVER}-${PKGREL}-x86_64.AppImage?job=appimage" *-x86_64.AppImage.zsync

mv *-x86_64.AppImage ../${PKGNAME}-${PKGVER}-${PKGREL}-x86_64.AppImage
mv *-x86_64.AppImage.zsync ../${PKGNAME}-${CI_COMMIT_REF_SLUG}-x86_64.AppImage.zsync